### ISSUE TITLE
Failed to compile with meson 1.4.0

### ISSUE THREAD

**Issue by SpidFightFR** [BuddiesOfBudgie/budgie-desktop-view#29]
Hello, i encounter a problem while compiling budgie-desktop-view using meson 1.4.0.
It used to work with meson 1.3.2, however after an update of meson, the build process fails with these errors:

I'm pretty sure i'm missing something, a dependency required after the meson 1.4.0 update, or a setting that needs to change using a patch... Anyway - something that i missed here.

Thank you by advance for your help. Don't hesitate to ping me or ask me if you need more info.
Logs [attached](https://gist.github.com/SpidFightFR/4334993fd69c5faa4ebc77230ee2dad6), it's a giant wall of text tho...

**Comment by meator** [comment]
It looks like Meson version `1.2.0` and `1.3.2` add the `-w` flag to the command line for some unknown reason. This negates all warning related flags, in particular:

```
-Werror -Wconversion -Wformat -Wformat-security -Wstack-protector -Wundef -Wuninitialized
```

Meson `1.4.0` appears to have fixed this bug (?), so warnings are enabled again. They cause the build to fail because of `-Werror`.

**Comment by JoshStrobl** [comment]
Duplicate of #28
